### ISSUE TITLE
Automatic unit testing of _main_ packages in komodo

### ISSUE THREAD

**Issue by jondequinor** [equinor/komodo#86]
We want to unit test each of the following packages for some `$RELEASE_NAME`:

- [x] ERT @sondreso https://github.com/equinor/ert/pull/679
- [x] libres @ManInFez equinor/libres#900
- [x] libecl @jondequinor  https://github.com/equinor/libecl/pull/693
- [x] semeio @ManInFez https://github.com/equinor/semeio/pull/40
- [x] equilibrium @ManInFez equinor/equilibrium#10
- [x] everest @jondequinor https://github.com/equinor/everest/pull/1199
- [x] spinningjenny @ManInFez equinor/spinningjenny#192

For consistency, the jenkins file should be named `ci/jenkins/Jenkinsfile-komodo`.
